# -*- coding: utf-8 -*-
"""COVID_19.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14HWkq-aZ2ho3htXu7lH1c8zAruBR1Npq
"""

import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
import sqlite3

from google.colab import files
uploaded=files.upload()

df_covid19=pd.read_csv("covid_19_clean_complete.csv")
df_covid19.head()

df_covid19.drop(columns=["Province/State"], inplace=True)   ## Blank Column removal

df_covid19.head()

df_covid19.info()
df_covid19.isnull().sum()

df_covid19["Country/Region"].nunique()  ### 187 unique countries are here in this dataset

df_covid19["WHO Region"].nunique() ## 6 WHO Region

connect=sqlite3.connect("COVID19.db")
df_covid19.to_sql("covid19", connect, if_exists="replace", index=False)

pd.read_sql_query("""select * from covid19 limit 3;""", connect)

"""## Top 10 Country with highest deaths  """

pd.read_sql_query("""select"Country/Region", max(deaths) as total_deaths, max("recovered") as total_recoverd,
                      max(active) as total_active from covid19
                      group by "Country/Region" order by max(deaths) desc limit 10;""", connect)
## US faced highest deaths 	11011411

### Top 10 Country with highest deaths

top_10= df_covid19.groupby("Country/Region")[["Confirmed", "Deaths", "Recovered", "Active"]].max().sort_values(by="Deaths", ascending=False).reset_index().head(10)
top_10
plt.figure(figsize=(9,6))
sns.barplot(x=top_10["Country/Region"], y=top_10["Deaths"], palette="magma")
plt.xticks(rotation=45)
plt.show()

"""## Highest number of new cases update over time"""

pd.read_sql_query("""
select "Country/Region" AS country,
    Date,
    Confirmed - coalesce(LAG(Confirmed) OVER (PARTITION BY [Country/Region] ORDER BY Date), 0) AS new_cases
FROM covid19 order by new_cases desc limit 1;
""", connect)

### United Kingdom has higest number of new cases.

"""## Top 10 countries with highest number of daily new cases"""

pd.read_sql_query("""
WITH daily_cases AS (
    SELECT
        "Country/Region" AS country,
        Date,
        Confirmed - COALESCE(LAG(Confirmed) OVER (PARTITION BY "Country/Region" ORDER BY Date), 0) AS new_cases FROM covid19 )
SELECT
    country,
    MAX(new_cases) AS max_daily_new_cases
FROM daily_cases
GROUP BY country
ORDER BY max_daily_new_cases DESC
LIMIT 10;
""", connect)

"""## Daily New COVID-19 Cases in all the  Countries"""

## Daily New COVID-19 Cases in all Countries

df_all_peak_Countries = pd.read_sql_query("""
SELECT * FROM (
    SELECT "Country/Region" AS country, Date, Confirmed - COALESCE(LAG(Confirmed) OVER
                         (PARTITION BY "Country/Region" ORDER BY Date), 0) AS new_cases FROM covid19) AS t
WHERE new_cases >= 0;
""", connect)

df_all_peak_Countries

df_all_peak_Countries["Date"] = pd.to_datetime(df_all_peak_Countries["Date"])


top10 = (
    df_all_peak_Countries.groupby("country")["new_cases"].max().sort_values(ascending=False).head(10).index
    .tolist()
)


# Filter dataset for only those 10 countries
df_top10 = df_all_peak_Countries[df_all_peak_Countries["country"].isin(top10)]

plt.figure(figsize=(14,7))
sns.lineplot(data=df_top10, x="Date", y="new_cases", hue="country")

plt.title("Daily New COVID-19 Cases — Top 10 Peak Countries", fontsize=14)
plt.xlabel("Date")
plt.ylabel("New Cases")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

"""## COVID 19 deaths over time in United Kingdom  """

df = pd.read_sql_query("""
SELECT
    "Country/Region" AS country,
    Date,
    Deaths
FROM covid19
WHERE "Country/Region" = 'United Kingdom'
ORDER BY Date;
""", connect)

df["Date"] = pd.to_datetime(df["Date"])

plt.figure(figsize=(14,7))
sns.lineplot(data=df, x="Date", y="Deaths")

plt.title("COVID-19 Deaths Over Time — United Kingdom")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

"""## COVID 19 deaths trend in WHO regions"""

pd.read_sql_query("select * from covid19", connect)

"""## Daily cases and deaths in WHO regions"""

df_who_trend = pd.read_sql_query("""SELECT "WHO Region" AS region, Date,
    sum(Confirmed) AS daily_cases,
    sum(Deaths) AS daily_deaths
FROM covid19
GROUP BY region, Date
ORDER BY region, Date;
""", connect)
df_who_trend

df_who_trend["Date"] = pd.to_datetime(df_who_trend["Date"])

plt.figure(figsize=(14,7))
sns.lineplot(data=df_who_trend, x="Date", y="daily_cases", hue="region")
plt.title("COVID-19 Daily Confirmed Cases Trend by WHO Region")
plt.xlabel("Date")
plt.ylabel("Total Confirmed Cases")
plt.xticks(rotation=45)
plt.tight_layout()                             ### America faced highest daily confirmed cases.
plt.show()

"""## Country wise case fatality and case recovery rates"""

df_country_rates = pd.read_sql_query("""
SELECT
    "Country/Region" AS country,
    MAX(Confirmed) AS total_confirmed,
    MAX(Deaths) AS total_deaths,
    MAX(Recovered) AS total_recovered,
    ROUND(MAX(Deaths)*100.0 / MAX(Confirmed), 4) AS case_fatality_rate,
    ROUND(MAX(Recovered)*100.0 / MAX(Confirmed), 4) AS case_recovery_rate
FROM covid19
GROUP BY "Country/Region"
HAVING Max(Confirmed) > 0
ORDER BY case_fatality_rate DESC limit 10;
""", connect)
df_country_rates   ### Yemen had highest case fatality rate and recovery rate dure is low population of confirmed cases (1691).

## The COVID-19 dataset contains cumulative daily totals,
## so using  SUM() would incorrectly inflate values by adding each day’s cumulative count.
## To obtain accurate final totals, MAX() is the correct choice because it represents the latest cumulative value for each country or region.

plt.figure(figsize=(9,6))
sns.barplot(data=df_country_rates, x="country", y="case_fatality_rate", palette="magma")
plt.title("Case Fatality Rate (CFR) by Country")
plt.xlabel("Country")
plt.ylabel("Case Fatality Rate")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

"""## WHO region wise case fatality rate and case recovery rate  """

df_region_rates = pd.read_sql_query("""
SELECT
    "WHO Region" AS region,
    MAX(Confirmed) AS total_confirmed,
    MAX(Deaths) AS total_deaths,
    MAX(Recovered) AS total_recovered,
    ROUND(MAX(Deaths)*100.0 / MAX(Confirmed), 2) AS case_fatality_rate,
    ROUND(MAX(Recovered)*100.0 / MAX(Confirmed), 2) AS case_recovery_rate
FROM covid19
GROUP BY "WHO Region"
HAVING MAX(Confirmed) > 0
ORDER BY case_fatality_rate DESC;
""", connect)
df_region_rates
                             ### Europe has the highest case fatality rate.

"""## WHO region wise case fatality and recovery rates"""

df_who_region=pd.read_sql_query("""
Select "WHO Region",
       max(Confirmed) AS total_confirmed_cases,
       max(Deaths) AS total_deaths,
        ROUND(MAX(Deaths) * 100.0 / MAX(Confirmed), 2) AS case_fatality_rate,
         ROUND(MAX(Recovered) * 100.0 / MAX(Confirmed), 2) AS case_recovery_rate
FROM covid19
GROUP BY "WHO Region"
ORDER BY total_deaths DESC;
""", connect)
df_who_region                    ### Europe has highest case fatality rate amoung all the WHO regions

plt.figure(figsize=(10,6))
sns.barplot(data=df_region_rates, x="region", y="case_fatality_rate", palette="viridis")
plt.title("Case Fatality Rate (CFR) by WHO Region")
plt.xlabel("WHO Region")
plt.ylabel("Case Fatality Rate")
plt.xticks(rotation=45)
plt.show()

"""## Correlation analysis of Confirmed and Deaths"""

# Load final-country totals (since Confirmed/Deaths are cumulative daily values)
df_correlation = pd.read_sql_query("""
select
    "Country/Region" AS country,
    max(Confirmed) AS confirmed,
    max(Deaths) AS deaths,
    max(Recovered) AS recovered
from covid19
group by  "Country/Region"
having confirmed > 0;
""", connect)

corr_confirmed_deaths = df_correlation['confirmed'].corr(df_correlation['deaths'])

corr_confirmed_deaths               ### strong correlation between confirmed cases and deaths (0.934)

plt.figure(figsize=(8,6))
sns.regplot (x=df_correlation["confirmed"], y=df_correlation["deaths"])

plt.title("Correlation: Confirmed Cases vs Deaths")
plt.xlabel("Total Confirmed Cases")
plt.ylabel("Total Deaths")
plt.tight_layout()
plt.show()

plt.figure(figsize=(6,4))
sns.heatmap(df_correlation[['confirmed', 'deaths', 'recovered']].corr(),
            annot=True, cmap="coolwarm")

plt.title("heat map(Confirmed, Deaths, Recovered)")
plt.tight_layout()
plt.show()

"""## Statistical analysis of CFR over regions

---


"""

df_cfr = pd.read_sql_query("""
SELECT
    "Country/Region" AS country,
    "WHO Region" AS region,
    MAX(Deaths) * 100.0 /MAX(Confirmed) AS CFR
FROM covid19
GROUP BY "Country/Region"

""", connect)

df_cfr.groupby("region")["CFR"].count()

import scipy.stats as stats

from scipy.stats import f_oneway

# Unique WHO regions
regions = df_cfr['region'].unique()

# Prepare groups for ANOVA (CFR values per region)
groups = [df_cfr[df_cfr['region'] == r]['CFR'] for r in regions]

# Run ANOVA
anova_result = f_oneway(*groups)

anova_result

"""When including all countries, ANOVA detects significant differences in CFR across WHO regions (p = 0.0088).
However, when filtering out countries with fewer than 1000 confirmed cases, the difference is no longer statistically significant (p = 0.0539).
This indicates that extreme CFR values in small-population countries heavily influence the results, and regional differences are less pronounced among larger nations with more stable reporting.
"""

